name=d9dist
version=1.0.0
author=d9ll
maintainer=d9ll
sentence=Легкая библиотека для ультразвукового датчика расстояния с фильтрацией.
paragraph=Позволяет измерять дистанцию одной командой и проверять близость объекта через функцию near() без лишнего кода.
category=Sensors
url=https://github.com/d9ll/d9dist
architectures=*